"""add satisfaction column to students

Revision ID: 681b6f01c4c3
Revises: 
Create Date: 2025-12-18 08:18:27.251531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681b6f01c4c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_special_students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lab_id', sa.String(length=16), nullable=True),
    sa.Column('student_id', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['laboratories.lab_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matching_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('student_id', sa.String(length=16), nullable=True),
    sa.Column('assigned_lab', sa.String(length=16), nullable=True),
    sa.Column('satisfaction', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_lab'], ['laboratories.lab_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matching_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matching_results_batch_id'), ['batch_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('student_id', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_student_lab', ['student_id', 'lab_id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('satisfaction', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('satisfaction')

    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.drop_constraint('uq_student_lab', type_='unique')

    op.drop_table('users')
    with op.batch_alter_table('matching_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matching_results_batch_id'))

    op.drop_table('matching_results')
    op.drop_table('lab_special_students')
    # ### end Alembic commands ###
